name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test-nix-rustls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Build and test
        run: nix build ./nix-rustls#ci

  test-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Build and test
        run: nix build .#ci

  test-non-nix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - '9.2'
          - '9.4'
          - '9.6'
          - '9.8'
          - '9.10'
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Build rustls-ffi
        run: |
          cd ${{ runner.temp }}
          git clone https://github.com/rustls/rustls-ffi -b v0.14.0
          cd rustls-ffi
          make DESTDIR=${{ runner.temp }}/rustls install
      - name: Install CLI dependencies
        run: |
          nix profile install --inputs-from . \
            nixpkgs#minica \
            nixpkgs#miniserve

      - name: Configure
        run: |
          cabal configure --enable-tests \
            --extra-include-dirs ${{ runner.temp }}/rustls/include \
            --extra-lib-dirs     ${{ runner.temp }}/rustls/lib
      - name: Freeze build
        run: cabal freeze
      - uses: actions/cache@v4
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cabal-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            cabal-${{ matrix.ghc }}

      - name: Build dependencies
        run: cabal build all --only-dependencies
      - name: Build
        run: cabal build all
      - name: Run tests
        run: cabal test all
