name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test-nix-rustls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Build and test
        run: nix build ./nix-rustls#ci

  test-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Build and test
        run: nix build .#ci

  test-non-nix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - '9.2'
          - '9.4'
          - '9.6'
          - '9.8'
          - '9.10'
          - '9.12'
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Install rustls-ffi
        run: |
          cd ${{ runner.temp }}
          wget "https://github.com/rustls/rustls-ffi/releases/download/v${RUSTLS_VERSION}/librustls_${RUSTLS_VERSION}_amd64.deb.zip"
          7z x ./*.zip
          sudo dpkg -i ./*.deb
        env:
          RUSTLS_VERSION: '0.15.0'

      - name: Install CLI dependencies
        run: |
          nix profile install --inputs-from . \
            nixpkgs#minica \
            nixpkgs#miniserve

      - name: Freeze build
        run: cabal freeze
      - uses: actions/cache@v4
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cabal-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            cabal-${{ matrix.ghc }}

      - name: Build dependencies
        run: cabal build all --only-dependencies
      - name: Build
        run: cabal build all
      - name: Run tests
        run: cabal test all
